### PR TITLE
Added option to set HTML format.

### PR DESCRIPTION
**Pull request by foxycode**

### CODE REVIEW

**Comment by hrach** [comment]
The logic behind this is: always be strict in what you serve, be merficul what you accept. The idea is: generate always html5 valid datetime input. If some browser does not support it (or if you want), change it by javascript.

**Comment by hrach** [comment]
Do you agree? Maybe you need another usecase.. and this may be relevant for you.

**Comment by foxycode** [comment]
I don't agree, but understand your thoughts. What I need is to have fully functional form without JS and czech users have problems with Y-m-d dates. I use my forked version or create something else, I use only that one control from your package.

**Comment by hrach** [comment]
I see that htmlFormat is protected so no need for forking and I think we can let this be closed. Ok?

**Comment by foxycode** [comment]
You're right, I can just inherit. Ok, let it closed.

**Pull request closed without merging**
