### PR TITLE
Fix template trait

### LINKED ISSUE #51: Undefined variable: _form
Při aktualizaci jednoho staršího projektu na Nette 2.4 jsem narazil s vlastními komponentami, založenými na Nextras\Forms\ComponentControl.

Zjednodušený kód:

```php
class PublishingControl extends ComponentControl
{
	public function __construct($caption = NULL)
	{
		parent::__construct($caption);
		$this['draft'] = new Checkbox('Uložit draft, zatím nepublikovat');
		$this['datePublish'] = new DatePicker('Datum zveřejnění');
	}
}
```

šablona:
```html
<div class="form-group">
	<div class="checkbox">
		{input draft}
	</div>
</div>
<div id="{$toggleId}" class="form-group">
	{label datePublish class => "control-label" /}
	{input datePublish}
</div>
```

Nevím, zda tohle nějak nesouvisí s #49 . Pokud změním $_form na $form, změní se i hláška na "undefined variable: form".

"nextras/forms": "^2.0.1",
"nette/forms": "^2.4.6",
"latte/latte": "^2.4.6",

V configu:
extensions:
	nextras.form: Nextras\Forms\Bridges\NetteDI\FormsExtension

latte:
	macros:
		- Nextras\Forms\Bridges\Latte\Macros\BS3InputMacros

Pokud vypnu BS3InputMacros, nic se nezmění. Pokud neaktivuju rozšíření nextras, dostanu `end() expects parameter 1 to be array, null given`

Verze 1.6.2 ve spojení s 2.3.x Nette fungovala podle očekávání.

### PR DESCRIPTION
**Pull request by khorsky**
I haven't found a way, how to fix #51 yet, but with this hotfix it is possible to use nextras/forms in version 1.6.x with Nette 2.4.

Would it be possible to release v1.6.3 with these changes?

### CODE REVIEW

**Comment by hrach** [comment]
I have no idea what are you trying to achieve. 
- there is 2.0 version which is compatible with Nette 2.4
- there is 1.6 version which is compatible with Nette <2.4.

**Comment by hrach** [comment]
Sorry, still not getting what do you want or mean. maybe it would help if you rebase the PR to show what excatly are you wanna fix.

**Comment by khorsky** [comment]
I'm not a git guru - is rebase to a master really good idea? I checked out tag v1.6.2 to a separate branch and made changes.

Ah, may be I found out why this PR seems so strange to you - I tried the "Resolve conflicts" and it shows the changes against master - I've seen "only those with write access..." and thought it's an forbidden button for me.

"Resolve conflicts" makes no sense to me either, you've updated 2.0 a lot. "Files changed" might be more helpful. I suppose I should have done PR against something else - but there is no "old" 1.6 branch and I haven't found a way, how to make PR against tag - i believe it's not possible.

Sorry, I'm git beginner. Is there anything I could do right now to help?

**Comment by khorsky** [comment]
Is there any chance that you would open 1.6x branch, so I could resend the PR to the correct branch?

It will allow people use 1.6.x version with Nette 2.4 until the "Undefined variable: _form" error in 2.0.x version is solved. Or - they cannot use {label}, {input} macros in their control templates.

I'm not able to describe the problem in a better way.

**Comment by hrach** [comment]
I do not want to maintain old version compatibility, co I rather fixed 2.0 branch, please try https://github.com/nextras/forms/releases/tag/v2.0.2 :)

**Pull request closed without merging**
