### PR TITLE
Improve compatibility with raw Nette/Forms

### PR DESCRIPTION
**Pull request by Trejjam**
Hi,

I found some problems with co-existence `Nextras/Forms` and raw `Nette/Forms` (without `Bs3FormRenderer`). I think `BS3InputMacros::input` macro could be used only for forms with `Bs3FormRenderer` (or ext).

Second change in `BS3InputMacros::input` is for support render own form-part using latte include 

Use case: pass `$form` into included block, and Nette 2.4 do not allow pass/redefine `$_form` - because it is deprecated.

### CODE REVIEW

**Comment by Trejjam** [comment]
Ping @nextras

**Comment by hrach** [comment]
Well, definitely Bs3Renderer is totally independent from Bs3Macros, they are not meant to be connect. 

Maybe the error is using _form instead $form or not directly passing the form.

**Comment by Trejjam** [comment]
Bs3* are not independent, both change together form into bootstrap form.

But my opinion is I do not expect changing raw form (with `DefaultFormRenderer`) by `Bs3Macros`. (Also they are not fully compatible, with `<input type=submit>` without `caption`)

I use `isset` clause because I think old Nette forms use `$_form`.

**Comment by hrach** [comment]
> yesBs3* are not independent

they are meant to be.

**Comment by Trejjam** [comment]
Ok, I am not sure about it. But maybe it is possible move this parts of code from `Bs3Macro` into [Bs3FormRenderer](https://github.com/nextras/forms/blob/master/src/Rendering/Bs3FormRenderer.php).

What do you think about it?

**Comment by hrach** [comment]
Sorry, I totaly don't understand what is the problem :) These two are independent and should stay independent.

**Comment by Trejjam** [comment]
Problem are legacy application with raw Nette Form and Nextras Bootstrap3 Form

**Comment by hrach** [comment]
Sorry, that sentenca doesn't state a problem. Post the wrong html output with some php code, or post some bluescreen, whatever what makes clear what is the wrong behavior.

**Comment by Trejjam** [comment]
```php
$form = new Form;
$form->addSubmit('submit');
```

Engine with Bs3Macro:
```latte
{control componentName}
```

Throw `Nette\InvalidArgumentException` because submit have not `caption/label`. Normally browser use default `<input type=submit>` label - this is what I expect if I do not use Bs3Renderer.

**Comment by hrach** [comment]
I personally tested that macros correctly works without setting the renderer.
Ad the 2.4 compatibility: I fixed it in https://github.com/nextras/forms/releases/tag/v2.0.2, please try if it fixed your issues.

**Pull request closed without merging**
