### PR TITLE
fixed bs3 label compatibility with nette 2.4

### PR DESCRIPTION
**Pull request by attreid**

### CODE REVIEW

**Comment by jtojnar** [comment]
Can you change the indentation back to tabs (for the diff to be usable)?

**Comment by hrach** [comment]
Actually, I thought it's fixed by https://github.com/nextras/forms/issues/38#issuecomment-244547819. cc @trejjam If it's still not fixed, imo it's something what should be ideally fixed on the Nette side. Will try to test.

**Comment by attreid** [comment]
Yes, it's fixed by #38

**Comment by hrach** [comment]
@attreid Thanks for verification! :-)

**Pull request closed without merging**
